<!DOCTYPE html>
<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <title><?php echo $cedente; ?></title>
        <style type="text/css">
            /* Embed the CSS content here */
            <?php include $resource_path . '/css/styles.css' ?>
        </style>
    </head>
    <body>

        <div style="width: 666px">
            <div class="noprint info">
                <h2>Instruções de Impressão</h2>
                <ul>
                    <li>Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo econômico).</li>
                    <li>Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.</li>
                    <li>Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o código de barras.</li>
                    <li>Caso não apareça o código de barras no final, pressione F5 para atualizar esta tela.</li>
                    <li>Caso tenha problemas ao imprimir, copie a sequencia numérica abaixo e pague no caixa eletrônico ou no internet banking:</li>
                </ul>
                <span class="header">Linha Digitável: <?php echo $linha_digitavel; ?></span>
                <?php if ($valor_documento) : ?><span class="header">Valor: R$ <?php echo $valor_documento; ?></span><?php endif ?>
                <?php if ($pagamento_minimo) : ?><span class="header">Pagamento mínimo: R$ <?php echo $pagamento_minimo; ?></span><?php endif ?>
                <br>
                <div class="linha-pontilhada" style="margin-bottom: 20px;">Recibo do pagador</div>
            </div>

            <div class="info-empresa">
                <?php if ($logotipo) : ?>
                    <div style="display: inline-block;">
                        <img alt="logotipo" src="<?php echo $logotipo; ?>" />
                    </div>
                <?php endif ?>
                <div style="display: inline-block; vertical-align: super;">
                    <div><strong><?php echo $cedente; ?></strong></div>
                    <div><?php echo $cedente_cpf_cnpj; ?></div>
                    <div><?php echo $cedente_endereco1; ?></div>
                    <div><?php echo $cedente_endereco2; ?></div>
                </div>
            </div>
            <br>

            <table class="table-boleto" cellpadding="0" cellspacing="0" border="0">
                <tbody>
                    <tr>
                        <td valign="bottom" colspan="8" class="noborder nopadding">
                            <div class="logocontainer">
                                <div class="logobanco">
                                    <img src="<?php echo $logo_banco; ?>" alt="logotipo do banco">
                                </div>
                                <div class="codbanco"><?php echo $codigo_banco_com_dv ?></div>
                            </div>
                            <div class="linha-digitavel"><?php echo $linha_digitavel ?></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" width="250">
                            <span class="titulo">Beneficiário</span><br>
                            <span class="conteudo"><?php echo $cedente ?> <?php echo $cedente_endereco1; ?> <?php echo $cedente_endereco2; ?> </span>
                        </td>
                        <td>
                            <span class="titulo">CPF/CNPJ</span><br>
                            <span class="conteudo"><?php echo $cedente_cpf_cnpj ?></span>
                        </td>
                        <td width="120">
                            <span class="titulo">Agência/Código do Beneficiário</span><br>
                            <div class="rtl"><span class="conteudo"><?php echo $agencia_codigo_cedente ?></span></div>
                        </td>
                        <td width="110">
                            <span class="titulo">Vencimento</span><br>
                            <div class="rtl"><span class="conteudo "><?php echo $data_vencimento ?></span></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <span class="titulo">Pagador</span><br>
                            <span class="conteudo"><?php echo $sacado ?> <?php echo $sacado_endereco1; ?> <?php echo $sacado_endereco2; ?></span>
                        </td>
                        <td colspan="1">
                            <span class="titulo">CPF/CNPJ</span><br>
                            <span class="conteudo"><?php echo $sacado_documento; ?></span>
                        </td>
                        <td>
                            <span class="titulo">Nº documento</span><br>
                            <div class="rtl"><span class="conteudo"><?php echo $numero_documento ?></span></div>
                        </td>
                        <td>
                            <span class="titulo">Nosso número</span><br>
                            <div class="rtl"><span class="conteudo"><?php echo $nosso_numero ?></span></div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="titulo">Espécie</span><br>
                            <span class="conteudo"><?php echo $especie ?></span>
                        </td>
                        <td>
                            <span class="titulo">Quantidade</span><br>
                            <div class="rtl"><span class="conteudo"><?php echo $quantidade ?></span></div>
                        </td>
                        <td>
                            <span class="titulo">Valor</span><br>
                            <div class="rtl"><span class="conteudo"><?php echo $valor_unitario ?></span></div>
                        </td>
                        <td>
                            <span class="titulo">(-) Descontos / Abatimentos</span><br>
                            <div class="rtl"><span class="conteudo"><?php echo $desconto_abatimento ?></span></div>
                        </td>
                        <td>
                            <span class="titulo">(=) Valor Documento</span><br>
                            <div class="rtl"><span class="conteudo"><?php echo $valor_documento ?></span></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <span class="titulo">Demonstrativo</span><br>
                            <span class="conteudo">
                            <?php echo $demonstrativo[0] ?>
                                <?php echo ($demonstrativo[1])?'<br>':'';?><?php echo $demonstrativo[1] ?>
                                <?php echo ($demonstrativo[2])?'<br>':'';?><?php echo $demonstrativo[2] ?>
                                <?php echo ($demonstrativo[3])?'<br>':'';?><?php echo $demonstrativo[3] ?>
                                <?php echo ($demonstrativo[4])?'<br>':'';?><?php echo $demonstrativo[4] ?>
                            </span>
                        </td>
                        <td>
                            <span class="titulo">(-) Outras deduções</span><br>
                            <span class="conteudo"><?php echo $outras_deducoes ?></span>
                        </td>
                        <td>
                            <span class="titulo">(+) Outros acréscimos</span><br>
                            <div class="conteudo rtl"><?php echo $outros_acrescimos ?></span>
                        </td>
                        <td>
                            <span class="titulo">(=) Valor cobrado</span><br>
                            <div class="rtl"><span class="conteudo"><?php echo $valor_cobrado ?></span></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="5" class="bottomborder">
                            <span class="titulo">Detalhamento</span><br>
                            <span class="conteudo"><?php echo $detalhamento;?></span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <br>
            <div class="linha-pontilhada">Corte na linha pontilhada</div>
            <br>

            <!-- Ficha de compensação -->
            <?php include('partials/ficha-de-compensacao.phtml') ?>
        </div>
    </body>
</html>