<!--
 * OpenBoleto - Geração de boletos bancários em PHP
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following
 * conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies
 * or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-->

<table class="table-boleto" cellpadding="0" cellspacing="0" border="0">
    <tbody>
        <tr>
            <td valign="bottom" colspan="8" class="noborder nopadding">
                <div class="logocontainer">
                    <div class="logobanco">
                        <img src="<?php echo $logo_banco; ?>" alt="logotipo do banco">
                    </div>
                    <div class="codbanco"><?php echo $codigo_banco_com_dv ?></div>
                </div>
                <div class="linha-digitavel"><?php echo $linha_digitavel ?></div>
            </td>
        </tr>
        <tr>
            <td colspan="7">
                <span class="titulo">Local de pagamento</span><br>
                <span class="conteudo"><?php echo $local_pagamento ?></span>
            </td>
            <td width="180">
                <span class="titulo">Vencimento</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $data_vencimento ?></span></div>
            </td>
        </tr>
        <tr style="height: 39px;">
            <td colspan="6">
                <span class="titulo">Beneficiário</span><br>
                <span class="conteudo"><?php echo $cedente ?> <?php echo $cedente_endereco1; ?> <?php echo $cedente_endereco2; ?></span>
            </td>
            <td colspan="1">
                <span class="titulo">CPF/CNPJ</span><br>
                <span class="conteudo"><?php echo $cedente_cpf_cnpj; ?></span>
            </td>
            <td>
                <span class="titulo">Agência/Código beneficiário</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $agencia_codigo_cedente ?></span></div>
            </td>
        </tr>
        <tr>
            <td width="110" colspan="2">
                <span class="titulo">Data do documento</span><br>
                <span class="conteudo"><?php echo $data_documento ?></span>
            </td>
            <td width="120" colspan="2">
                <span class="titulo">Nº documento</span><br>
                <span class="conteudo"><?php echo $numero_documento ?></span>
            </td>
            <td width="60">
                <span class="titulo">Espécie doc.</span><br>
                <span class="conteudo"><?php echo $especie_doc ?></span>
            </td>
            <td>
                <span class="titulo">Aceite</span><br>
                <span class="conteudo"><?php echo $aceite ?></span>
            </td>
            <td width="110">
                <span class="titulo">Data processamento</span><br>
                <span class="conteudo"><?php echo $data_processamento ?></span>
            </td>
            <td>
                <span class="titulo">Nosso número</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $nosso_numero ?></span></div>
            </td>
        </tr>
        <tr>
            <?php if (!$esconde_uso_banco) : ?>
                <td<?php if (!$mostra_cip) : ?> colspan="2"<?php endif ?>>
                    <span class="titulo">Uso do banco</span><br>
                    <span class="conteudo"><?php echo $uso_banco ?></span>
                </td>
            <?php endif; ?>

            <?php if ($mostra_cip) : ?>
                <!-- Campo exclusivo do Bradesco -->
                <td width="20">
                    <span class="titulo">CIP</span><br>
                    <span class="conteudo"><?php echo $cip ?></span>
                </td>
            <?php endif ?>

            <td<?php if ($esconde_uso_banco) : ?> colspan="3"<?php endif; ?>>
                <span class="titulo">Carteira</span><br>
                <span class="conteudo"><?php echo $carteira ?></span>
            </td>
            <td width="35">
                <span class="titulo">Espécie</span><br>
                <span class="conteudo"><?php echo $especie ?></span>
            </td>
            <td colspan="2">
                <span class="titulo">Quantidade</span><br>
                <span class="conteudo"><?php echo $quantidade ?></span>
            </td>
            <td width="110">
                <span class="titulo">Valor</span><br>
                <span class="conteudo"><?php echo $valor_unitario ?></span>
            </td>
            <td>
                <span class="titulo">(=) Valor do Documento</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $valor_documento ?></span></div>
            </td>
        </tr>
        <tr>
            <td colspan="7">
                <span class="titulo">Instruções (Texto de responsabilidade do beneficiário)</span>
            </td>
            <td>
                <span class="titulo">(-) Descontos / Abatimentos</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $desconto_abatimento ?>&nbsp;</span></div>
            </td>
        </tr>
        <tr>
            <td colspan="7" class="notopborder">
                <span class="conteudo"><?php echo $instrucoes[0]; ?>&nbsp;</span><br>
                <span class="conteudo"><?php echo $instrucoes[1]; ?>&nbsp;</span>
            </td>
            <td>
                <span class="titulo">(-) Outras deduções</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $outras_deducoes ?></span></div>
            </td>
        </tr>
        <tr>
            <td colspan="7" class="notopborder">
                <span class="conteudo"><?php echo $instrucoes[2]; ?>&nbsp;</span><br>
                <span class="conteudo"><?php echo $instrucoes[3]; ?>&nbsp;</span>
            </td>
            <td>
                <span class="titulo">(+) Mora / Multa</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $mora_multa ?></span></div>
            </td>
        </tr>
        <tr>
            <td colspan="7" class="notopborder">
                <span class="conteudo"><?php echo $instrucoes[4]; ?>&nbsp;</span><br>
                <span class="conteudo"><?php echo $instrucoes[5]; ?>&nbsp;</span>
            </td>
            <td>
                <span class="titulo">(+) Outros acréscimos</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $outros_acrescimos ?>&nbsp;</span></div>
            </td>
        </tr>
        <tr>
            <td colspan="7" class="notopborder">
                <span class="conteudo"><?php echo $instrucoes[6]; ?>&nbsp;</span><br>
                <span class="conteudo"><?php echo $instrucoes[7]; ?>&nbsp;</span>
            </td>
            <td>
                <span class="titulo">(=) Valor cobrado</span><br>
                <div class="rtl"><span class="conteudo"><?php echo $valor_cobrado ?></span></div>
            </td>
        </tr>
        <tr>
            <td colspan="7">
                <span class="titulo">Pagador</span><br>
                <span class="conteudo"><?php echo $sacado ?></span><br>
                <span class="conteudo"><?php echo $sacado_documento ?></span><br>
                <span class="conteudo"><?php echo $sacado_endereco1 ?></span><br>
                <span class="conteudo"><?php echo $sacado_endereco2 ?></span>
            </td>
            <td class="noleftborder">
                <span class="titulo" style="margin-top: 50px">Cód. Baixa</span><br>
            </td>
        </tr>

        <tr>
            <td colspan="6" class="noleftborder">
                <span class="titulo">Sacador/Avalista <span class="conteudo sacador"><?php echo $sacador_avalista; ?></span></span>
            </td>
            <td colspan="2" class="norightborder noleftborder">
                <div class="conteudo noborder rtl">Autenticação mecânica - Ficha de Compensação</div>
            </td>
        </tr>

        <tr>
            <td colspan="8" class="noborder">
                <?php echo $codigo_barras ?>
            </td>
        </tr>

    </tbody>
</table>